openapi: "3.0.0"
info:
  version: 1.0.0
  title: Link Shortener v2
  description: It shortens links man idk
  license:
    name: We still gotta think of one, for now, the default is MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      summary: Show API Docs
      operationId: Show API Docs
      responses:
        200:
          description: Shows the page you're on right now
  /{slug}:
    get:
      summary: Redirect to long url
      operationId: Redirect
      parameters:
        - name: slug
          in: path
          required: true
          description: The id of the shortened link
          schema:
            type: string
      responses:
        302:
          description: Redirect to long url
        404:
          description: Cannot find a url that matches the slug

  /api/v2/shorten:
    post:
      description: "Shorten a url"
      operationId: Shorten
      tags:
        - API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/url-slug"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/url-slug"
        "500":
          description: "The slug is already in use"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
              examples:
                example1:
                  value:
                    error:
                      code: 500
                      message: "slug 'abc' is already in use"
  /api/v2/entries:
    get:
      description: "Gets all the entries in the database"
      operationId: Get Entries
      tags:
        - API
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/url-slug"
  /api/v2/reset-entries:
    delete:
      description: "Deletes all entries in the database"
      operationId: Delete Entries
      tags:
        - API
      responses:
        "200":
          description: OK

components:
  schemas:
    url-slug:
      required:
        - slug
        - url
      properties:
        slug:
          type: string
        url:
          type: string
      example:
        slug: "abc"
        url: "http://google.com"
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
