version: "3.8"

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - linkShortenerData:/var/lib/mysql
  api:
    build: ./api
    ports:
      - 6969:6969
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mysql
  api-docs:
    build: ./api-docs
    ports:
      - 8000:80
    volumes:
      - ./api-docs:/usr/share/nginx/html:ro
    depends_on:
      - api
      
volumes:
  linkShortenerData:
    
