version: "3.8"

services:
  swagger:
    image: swaggerapi/swagger-editor
    ports:
      - 3000:8080
    environment:
      - SWAGGER_FILE=/tmp/api-docs.yaml
    volumes:
      - ./api-docs.yaml:/tmp/api-docs.yaml