version: '3.8'

services:
  mysql:
    image: mysql:8
    ports: 
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: link_shortener_db
    volumes:
      - link-shortener-2:/var/lib/mysql
  
  backend:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/backend
      - /backend/node_modules
    depends_on: 
      - mysql

volumes:
  link-shortener-2:
