name: Deploy to Google Cloud Compute Engine
on: push

env:
  GCP_PROJECT: exalted-booster-377120
  GCP_ZONE: us-central1-c
  GCP_INSTANCE: playground

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        id: auth
        with:
          create_credentials_file: "true"
          workload_identity_provider: projects/377961128619/locations/global/workloadIdentityPools/pool/providers/provider-id
          service_account: service-id@exalted-booster-377120.iam.gserviceaccount.com

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - id: "compute-ssh"
        uses: "google-github-actions/ssh-compute@v0"
        with:
          project_id: ${{ env.GCP_PROJECT }}
          instance_name: ${{ env.GCP_INSTANCE }}
          zone: ${{ env.GCP_ZONE }}
          ssh_private_key: "${{ secrets.GCP_SSH_PRIVATE_KEY_PLAYGROUND }}"
          flags: "--troubleshoot --tunnel-through-iap"
          command: |
            sudo apt-get update 
            sudo apt-get install -y docker.io
            sudo docker pull hello-world
            sudo docker run hello-world
