# How to setup Google Cloud Compute Engine with Workload identity provider

# Step 1: Create a Google Cloud Platform account
# Step 2: Create a project
# Step 3: Create a service account
# Step 4: Grant this service account access to the project
#          - Compute Admin
#          - workload identity user
# Step 5: Copy the service account email address: service-id@exalted-booster-377120.iam.gserviceaccount.com
# note:we don't need a key for this service account because we will use workload identity provider
# Step: 6: Create a workload identity pool
# Step: 7: Create a workload identity provider
#          - Provider type: OIDC
#          - Issuer URL:  https://token.actions.githubusercontent.com
# Step: 8: Copy the identity provider Url: https://iam.googleapis.com/projects/377961128619/locations/global/workloadIdentityPools/pool/providers/provider-id
# Step: 9: Configure provider attributes
#          - google.subject = assertion.sub # identity of the user or service that is executing the Github Actions
# Step 10: Select the workload identity provider you created in step 7 Grant Access to the service account
#        - Select the service account you created in step3
#        - Paste the OIDC provider URL you copied in step 8 in the Workload Identity Provider field
#        - format type: JSON
# Step 11: Create a workflow file (Below is an example workflow file)

name: Deploy to Google Cloud Compute Engine
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: https://iam.googleapis.com/projects/377961128619/locations/global/workloadIdentityPools/pool/providers/provider-id
          service_account: service-id@exalted-booster-377120.iam.gserviceaccount.com

      - name: "Use gcloud CLI"
        run: "gcloud info"
