name: Publish
on:
  push:
    branches:
      - main
# The following environment variables are required for the workflow to run
env:
  REGISTRY: ghrc.io
  IMAGE_NAME: ${{ github.repository.name }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: echo ${{ github.repository }}
      - run: echo ${{ github.repository.name }}
      - run: echo ${{ github.repository.owner }}
