name: Publish
on:
  push:
    branches:
      - 'main'
# The following environment variables are required for the workflow to run
env:
  REGISTRY: ghrc.io
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo $IMAGE_NAME_LC
      - run: echo 'Hello World'
      - run: echo ${{ github.actions.repository.name }}
      - run: echo ${{ github.actor}}
      - run: echo ${{ github.repository }}
      - run: echo ${{ github.repository.owner.login }}
      - run: echo ${{ github.event.pull_request.head.repo.owner.login }}
      - run: echo  ${{ github.actor }}

  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lowercase/Build/tag/login/push the latest image
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >>${GITHUB_ENV}
          docker build -t $REGISTRY/$IMAGE_NAME:latest .
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          docker push $REGISTRY/$IMAGE_NAME
        env:
          IMAGE_NAME: '${{ github.repository }}'
          CR_PAT: ${{ secrets.CR_PAT }}

        # uses: actions/github-login@v3
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
        #   registry: ${{ env.REGISTRY }}
        #   organization: ${{ github.organization }}
        #   repository: ${{ github.repository }}
        #   tag: latest
        #   action: login
  pull-and-run-image-on-vultr:
    name: Pull and run image on Vultr
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - run: echo 'Next step is server connections'

      # - name: Pull the image from the Github Container Registry
      #   run: docker pull $REGISTRY/$IMAGE_NAME:latest
      # - name: Run the image
      #   run: docker run -it $REGISTRY/$IMAGE_NAME:latest
      # - name: Log out of the Github Container Registry
      #   run: docker logout
