name: Publish
on:
  push:
    branches:
      - 'main'
# The following environment variables are required for the workflow to run
env:
  REGISTRY: ghcr.io
  PAT: ${{ secrets.CR_PAT }}
  HOSTNAME: ${{ secrets.VULTR_IP }}
  USER: ${{ secrets.VULTR_USER }}
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor}} # => Madeeha-Anjum
      - run: echo ${{ github.repository }} # => Madeeha-Anjum/actions-playground

  # build-and-push-image:
  #   name: Build and push image
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: set lower case owner name
  #       env:
  #         IMAGE_NAME: '${{ github.repository }}'
  #       run: echo "IMAGE_NAME=${IMAGE_NAME,,}" >>${GITHUB_ENV}

  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  # - name: Log in to the Container registry
  #   uses: docker/login-action@v2
  #   with:
  #     registry: ${{ env.REGISTRY }}
  #     username: ${{ github.actor }}
  #     password: ${{ secrets.GITHUB_TOKEN }}

  # - name: Build/tag/login/push the latest image
  #   run: |
  #     docker build -t $REGISTRY/$IMAGE_NAME:latest .
  #     echo $PAT | docker login ghcr.io -u USERNAME --password-stdin
  #     docker push $REGISTRY/$IMAGE_NAME
  #   env:
  #     # using custom PAT
  #     CR_PAT: PAT

  pull-and-run-image-on-vultr:
    name: Pull and run image on Vultr
    runs-on: ubuntu-latest
    # needs:
    #   - build-and-push-image

    steps:
      - name: SSH Command with key
        run: |
          echo $USER@$HOSTNAME
          mkdir ~/.ssh
          echo $SSH_KEY >> ~/.ssh/github-action
          chmod 600 ~/.ssh/github-action

      - name: Add known_hosts
        run: |
          ssh-keyscan -t rsa $HOSTNAME >> ~/.ssh/known_hosts

      - name: SSH into Vultr server using private key
        run: ssh -T -i ~/.ssh/github-action $USER@$HOSTNAME

      - name: Install Docker if not installed
        run: echo "Installing Docker"

      - name: Pull image from Github Container registry
        run: echo "PULL IMAGE"

        # # https://github.com/marketplace/actions/ssh-remote-commands
        # uses: appleboy/ssh-action@master
        # with:
        #   host: ${{ env.HOSTNAME }}
        #   username: ${{ env.USER }}
        #   key: ${{ env.SSH_KEY }}

        # script: |
        #   docker pull ghcr.io/madeeha-anjum/actions-playground:latest
        #   docker run -d -p 80:80 ghcr.io/madeeha-anjum/actions-playground:latest

      # - name: Pull the image from the Github Container Registry
      #   run: docker pull $REGISTRY/$IMAGE_NAME:latest
      # - name: Run the image
      #   run: docker run -it $REGISTRY/$IMAGE_NAME:latest
      # - name: Log out of the Github Container Registry
      #   run: docker logout
