name: Publish
on:
  push:
    branches:
      - 'main'
# The following environment variables are required for the workflow to run
env:
  REGISTRY: ghcr.io
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor}} # => Madeeha-Anjum
      - run: echo ${{ github.repository }} # => Madeeha-Anjum/actions-playground

  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: set lower case owner name
        env:
          IMAGE_NAME: '${{ github.repository }}'
        run: echo "IMAGE_NAME=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Log in to the Container registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/tag/login/push the latest image(Login Way2)
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest .
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          docker push $REGISTRY/$IMAGE_NAME
        env:
          # using custom PAT
          CR_PAT: ${{ secrets.CR_PAT }}

  pull-and-run-image-on-vultr:
    name: Pull and run image on Vultr
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - run: echo 'Next step is server connections'

      # - name: Pull the image from the Github Container Registry
      #   run: docker pull $REGISTRY/$IMAGE_NAME:latest
      # - name: Run the image
      #   run: docker run -it $REGISTRY/$IMAGE_NAME:latest
      # - name: Log out of the Github Container Registry
      #   run: docker logout
